version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: santander_bootcamp
    extra_hosts:
      - "host.docker.internal:172.17.0.1"